import { createFeature, createReducer, createSelector, on } from "@ngrx/store";
import { OrderState } from "./order.state";
import { orderActions } from "./order.actions";


export const initialOrderState: OrderState = {
  order: null,
  isLoading: false,
  error: null,
}

export const orderFeature = createFeature({
  name: 'order',
  reducer: createReducer(
    initialOrderState,
    // Load Order
    on(orderActions.loadOrder, (state) => ({
      ...state,
      isLoading: true,
    })),
    on(orderActions.loadOrderSuccess, (state, action) => ({
      ...state,
      isLoading: false,
      order: action.order,
    })),
    on(orderActions.loadOrderFailure, (state, action) => ({
      ...state,
      isLoading: false,
      error: action.error,
    })),

    // Add Item
    on(orderActions.addItem, (state) => ({
      ...state,
      isLoading: true,
    })),
    on(orderActions.addItemSuccess, (state, { order }) => ({
      ...state,
      isLoading: false,
      order,
    })),
    on(orderActions.addItemFailure, (state, { error }) => ({
      ...state,
      isLoading: false,
      error
    })),

    // Remove Item
    on(orderActions.removeItem, (state) => ({
      ...state,
      isLoading: true,
    })),
    on(orderActions.removeItemSuccess, (state, { order }) => ({
      ...state,
      isLoading: false,
      order,
    })),
    on(orderActions.removeItemFailure, (state, { error }) => ({
      ...state,
      isLoading: false,
      error
    })),

    // Update Item Quantity
    on(orderActions.updateItemQuantity, (state) => ({
      ...state,
      isLoading: true,
    })),
    on(orderActions.updateItemQuantitySuccess, (state, { order }) => ({
      ...state,
      isLoading: false,
      order,
    })),
    on(orderActions.updateItemQuantityFailure, (state, { error }) => ({
      ...state,
      isLoading: false,
      error
    })),
    // Clear Orders
    on(orderActions.clearOrders, (state) => ({
      ...state,
      isLoading: true
    })),
    on(orderActions.clearOrdersSuccess, (state, { order }) => ({
      ...state,
      isLoading: false,
      order,
    })),
    on(orderActions.clearOrdersFailure, (state, { error }) => ({
      ...state,
      isLoading: false,
      error
    })),
  ),
});

// selectors auto generated by createFeature
export const {
  name: orderFeatureKey,
  reducer: orderReducer,
  selectOrderState,
  selectIsLoading,
  selectError,
  selectOrder,
} = orderFeature;

// Computed selectors (best practice: calculations in selectors, not reducers)
export const selectComputedTotalItems = createSelector(
  selectOrder,
  (order) => order?.items.reduce((total, item) => total + item.quantity, 0) ?? 0
);

export const selectComputedTotalPrice = createSelector(
  selectOrder,
  (order) => order?.items.reduce((total, item) => total + (item.quantity * item.price), 0) ?? 0
);
