import { createFeature, createReducer, on } from "@ngrx/store";
import { OrderState } from "../order-state";
import { orderActions } from "./actions";


export const initialOrderState: OrderState = {
  order: null,
  isLoading: false,
  error: null,
  totalItems: 0,
  totalPrice: 0,
}

export const orderFeature = createFeature({
  name: 'order',
  reducer: createReducer(
    initialOrderState,
    // Load Order
    on(orderActions.loadOrder, (state) => ({
      ...state,
      isLoading: true,
    })),
    on(orderActions.loadOrderSuccess, (state, action) => ({
      ...state,
      isLoading: false,
      order: action.order,
      totalItems: action.order.items.reduce((total, item) => total + item.quantity, 0),
      totalPrice: action.order.items.reduce((total, item) => total + (item.quantity * 10), 0),
    })),
    on(orderActions.loadOrderFailure, (state, action) => ({
      ...state,
      isLoading: false,
      error: action.error,
    })),

    // Add Item
    on(orderActions.addItem, (state) => ({
      ...state,
      isLoading: true,
    })),
    on(orderActions.addItemSuccess, (state, { order }) => ({
      ...state,
      isLoading: false,
      order,
      totalItems: order.items.reduce((total, item) => total + item.quantity, 0),
      totalPrice: order.items.reduce((total, item) => total + (item.quantity * 10), 0),
    })),
    on(orderActions.addItemFailure, (state, { error }) => ({
      ...state,
      isLoading: false,
      error
    })),

    // Remove Item
    on(orderActions.removeItem, (state) => ({
      ...state,
      isLoading: true,
    })),
    on(orderActions.removeItemSuccess, (state, { order }) => ({
      ...state,
      isLoading: false,
      order,
      totalItems: order.items.reduce((total, item) => total + item.quantity, 0),
      totalPrice: order.items.reduce((total, item) => total + (item.quantity * 10), 0),
    })),
    on(orderActions.removeItemFailure, (state, { error }) => ({
      ...state,
      isLoading: false,
      error
    })),

    // Update Item Quantity
    on(orderActions.updateItemQuantity, (state) => ({
      ...state,
      isLoading: true,
    })),
    on(orderActions.updateItemQuantitySuccess, (state, { order }) => ({
      ...state,
      isLoading: false,
      order,
      totalItems: order.items.reduce((total, item) => total + item.quantity, 0),
      totalPrice: order.items.reduce((total, item) => total + (item.quantity * 10), 0),
    })),
    on(orderActions.updateItemQuantityFailure, (state, { error }) => ({
      ...state,
      isLoading: false,
      error
    })),
    // Clear Orders
    on(orderActions.clearOrders, (state) => ({
      ...state,
      order: null,
      totalItems: 0,
      totalPrice: 0,
    })),
  ),
});

// selectors auto generated by createFeature
export const {
  name: orderFeatureKey,
  reducer: orderReducer,
  selectOrderState,
  selectIsLoading,
  selectError,
  selectOrder,
  selectTotalItems,
  selectTotalPrice
} = orderFeature;
